# TO-DO: ASK FOR WIDTH AND LENGTH OF TREEHOUSE BASE

# TO-DO: ASK FOR HEIGHT OF TREEHOUSE

# TO-DO: CALCULATE THE AREA OF THE TWO WALLS RUNNING THE WIDTH OF THE TREEHOUSE

# TO-DO: CALCULATE THE AREA OF THE TWO WALLS RUNNING THE LENGTH OF THE TREEHOUSE

# COMBINE